name: macOS Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'
        
    - name: Build App
      run: |
        xcodebuild -project ProtonDrive-macOS/ProtonDrive-macOS.xcodeproj \
                  -scheme "ProtonDriveMac-Sparkle" \
                  -configuration Release \
                  -xcconfig ProtonDrive-macOS/ProtonDriveMac/BuildConfigs/ProtonDrive-Config-Release-External.xcconfig \
                  CODE_SIGN_IDENTITY="-" \
                  CODE_SIGNING_REQUIRED=NO
        
    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "Proton Drive" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --app-drop-link 600 185 \
          "build/ProtonDrive.dmg" \
          "build/Release/ProtonDrive.app"